creation of ArtistHeader component and its props
daini-rl/spotify-components pull request #1
Opened 2024-08-29 06:41 UTC by Tecuani1

**Cambios principales:**

1. Nuevo Componente ArtistHeader:

- Recibe cuatro props: headerImg, nameArtist, verified, y monthlyListeners.

- Muestra la imagen del artista con headerImg.

- Incluye una verificación visual si verified es true, mostrando un ícono de verificación junto a la etiqueta "Verified Artist".

- Formatea y muestra el número de oyentes mensuales utilizando toLocaleString() para agregar comas al número, y solo se muestra el párrafo si el número está disponible.

2. Integración del Componente en App:

- El componente ArtistHeader se utiliza dentro de App, extrayendo los datos del archivo data.js.

- Los datos son desestructurados para facilitar el acceso a profile y stats del objeto artistUnion.
![Captura desde 2024-08-29 00-31-24](https://github.com/user-attachments/assets/5730b11a-6a60-4249-b6f4-5046914841ae)

2024-08-29 15:16 UTC, josuemonroy2023 requested changes
También creo que el nombre del archivo del css podría cambiar. Pero es algo que preferiría que lo discutieran y llegaran a un acuerdo.

2024-08-29 15:16 UTC, josuemonroy2023 commented on src/App.jsx
> +import reactLogo from './assets/react.svg';
Hay varios imports que ya no se usan, hay que eliminar esas referencias.
Incluso estaría mejor si vieran la posibilidad de agregar esa regla al lint.

2024-08-29 15:16 UTC, josuemonroy2023 commented on src/components/ArtistHeader.css
> +.headerImg {
Algunos nombres de las clases están en kebab case y otras en camel case. Lo mejor es que usen una (kebab case). Y mantengan esa como estándar

2024-08-29 16:03 UTC, daini-rl reviewed
¿Por qué se agregaron otros archivos svg? no veo que se utilicen en algún lado

2024-08-29 16:54 UTC, Tecuani1 commented on src/App.jsx
> +import reactLogo from './assets/react.svg';
Vale los reviso

2024-08-29 16:57 UTC, Tecuani1 commented
Ha es que copié la carpeta donde tenía los svg de todos los botones del proyecto 5

2024-08-29 16:57 UTC, Tecuani1 commented on src/components/ArtistHeader.css
> +.headerImg {
De acuerdo también los reviso y los corrijo 😃

2024-08-30 17:23 UTC, daini-rl commented
> Ha es que copié la carpeta donde tenía los svg de todos los botones del proyecto 5

Si no están tan relacionados con este PR creo que podrías borrarlos, ya más adelante se importarán si se necesitan, aparte creo que @BrennDev tomó el camino de utilizar iconos de fontawesome. Igual podrían definir cómo será el uso de iconos si es que no lo han hecho.

2024-08-30 19:39 UTC, daini-rl approved these changes

2024-08-30 19:44 UTC, josuemonroy2023 requested changes

2024-08-30 19:44 UTC, josuemonroy2023 commented on src/App.css
> +
Está totalmente vacío el archivo?
Ya no se está ocupando para nada? Si es así sería mejor quitarlo. Aunque no sé si valga la pena que pongan algo.

2024-08-30 23:48 UTC, Tecuani1 commented
Cambios principales:

Nuevo Componente ArtistHeader:
Recibe cuatro props: headerImg, nameArtist, verified, y monthlyListeners.

Muestra la imagen del artista con headerImg.

Incluye una verificación visual si verified es true, mostrando un ícono de verificación junto a la etiqueta "Verified Artist".

Formatea y muestra el número de oyentes mensuales utilizando toLocaleString() para agregar comas al número, y solo se muestra el párrafo si el número está disponible.

Integración del Componente en App:
El componente ArtistHeader se utiliza dentro de App, extrayendo los datos del archivo data.js.

Los datos son desestructurados para facilitar el acceso a profile y stats del objeto artistUnion.

2024-08-30 23:49 UTC, merged